// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserActiveTokens = `-- name: CountUserActiveTokens :one
SELECT COUNT(*) FROM api_tokens
WHERE user_id = $1 AND is_active = true AND (expires_at IS NULL OR expires_at > NOW()) AND revoked_at IS NULL
`

func (q *Queries) CountUserActiveTokens(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActiveTokens, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiToken = `-- name: CreateApiToken :one
INSERT INTO api_tokens (user_id, subscription_id, name, token_hash, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, subscription_id, name, token_hash, is_active, created_at, last_used_at, expires_at, revoked_at
`

type CreateApiTokenParams struct {
	UserID         int32       `json:"user_id"`
	SubscriptionID int32       `json:"subscription_id"`
	Name           string      `json:"name"`
	TokenHash      string      `json:"token_hash"`
	IsActive       pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createApiToken,
		arg.UserID,
		arg.SubscriptionID,
		arg.Name,
		arg.TokenHash,
		arg.IsActive,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Name,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteApiToken = `-- name: DeleteApiToken :exec
DELETE FROM api_tokens
WHERE id = $1
`

func (q *Queries) DeleteApiToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteApiToken, id)
	return err
}

const getApiTokenByHash = `-- name: GetApiTokenByHash :one
SELECT id, user_id, subscription_id, name, token_hash, is_active, created_at, last_used_at, expires_at, revoked_at
FROM api_tokens
WHERE token_hash = $1
`

func (q *Queries) GetApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getApiTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Name,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getApiTokenByID = `-- name: GetApiTokenByID :one
SELECT id, user_id, subscription_id, name, token_hash, is_active, created_at, last_used_at, expires_at, revoked_at
FROM api_tokens
WHERE id = $1
`

func (q *Queries) GetApiTokenByID(ctx context.Context, id int32) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getApiTokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Name,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listExpiredApiTokens = `-- name: ListExpiredApiTokens :many
SELECT id, user_id, subscription_id, name, token_hash, is_active, created_at, last_used_at, expires_at, revoked_at
FROM api_tokens
WHERE expires_at IS NOT NULL AND expires_at < NOW() AND is_active = true
`

func (q *Queries) ListExpiredApiTokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listExpiredApiTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.Name,
			&i.TokenHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserApiTokens = `-- name: ListUserApiTokens :many
SELECT id, user_id, subscription_id, name, token_hash, is_active, created_at, last_used_at, expires_at, revoked_at
FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserApiTokens(ctx context.Context, userID int32) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listUserApiTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.Name,
			&i.TokenHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiToken = `-- name: RevokeApiToken :one
UPDATE api_tokens
SET is_active = false, revoked_at = NOW()
WHERE id = $1
RETURNING id, user_id, subscription_id, name, token_hash, is_active, created_at, last_used_at, expires_at, revoked_at
`

func (q *Queries) RevokeApiToken(ctx context.Context, id int32) (ApiToken, error) {
	row := q.db.QueryRow(ctx, revokeApiToken, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Name,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateApiTokenLastUsed = `-- name: UpdateApiTokenLastUsed :one
UPDATE api_tokens
SET last_used_at = NOW()
WHERE id = $1
RETURNING id, user_id, subscription_id, name, token_hash, is_active, created_at, last_used_at, expires_at, revoked_at
`

func (q *Queries) UpdateApiTokenLastUsed(ctx context.Context, id int32) (ApiToken, error) {
	row := q.db.QueryRow(ctx, updateApiTokenLastUsed, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Name,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
