// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID             int32            `json:"id"`
	UserID         int32            `json:"user_id"`
	SubscriptionID int32            `json:"subscription_id"`
	Name           string           `json:"name"`
	TokenHash      string           `json:"token_hash"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastUsedAt     pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	RevokedAt      pgtype.Timestamp `json:"revoked_at"`
}

type AuditLog struct {
	ID           int32            `json:"id"`
	UserID       pgtype.Int4      `json:"user_id"`
	Action       string           `json:"action"`
	ResourceType pgtype.Text      `json:"resource_type"`
	ResourceID   pgtype.Int4      `json:"resource_id"`
	Changes      []byte           `json:"changes"`
	StatusCode   pgtype.Int4      `json:"status_code"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Permissions []byte           `json:"permissions"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Subscription struct {
	ID                 int32            `json:"id"`
	UserID             int32            `json:"user_id"`
	SubscriptionPlanID int32            `json:"subscription_plan_id"`
	PlanType           string           `json:"plan_type"`
	IsActive           pgtype.Bool      `json:"is_active"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	RenewalDate        pgtype.Timestamp `json:"renewal_date"`
	MaxTokensPerMonth  int32            `json:"max_tokens_per_month"`
	CurrentUsage       pgtype.Int4      `json:"current_usage"`
	UsageResetDate     pgtype.Timestamp `json:"usage_reset_date"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type SubscriptionPlan struct {
	ID                int32            `json:"id"`
	Name              string           `json:"name"`
	PlanType          string           `json:"plan_type"`
	Description       pgtype.Text      `json:"description"`
	MaxTokensPerMonth int32            `json:"max_tokens_per_month"`
	MaxApiCallsPerDay int32            `json:"max_api_calls_per_day"`
	Price             pgtype.Numeric   `json:"price"`
	Features          []byte           `json:"features"`
	TrialDurationDays pgtype.Int4      `json:"trial_duration_days"`
	IsActive          pgtype.Bool      `json:"is_active"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type TokenUsageLog struct {
	ID           int32            `json:"id"`
	ApiTokenID   int32            `json:"api_token_id"`
	UserID       int32            `json:"user_id"`
	Endpoint     string           `json:"endpoint"`
	Method       string           `json:"method"`
	StatusCode   int32            `json:"status_code"`
	ResponseTime pgtype.Int8      `json:"response_time"`
	DataSize     pgtype.Int8      `json:"data_size"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID            int32            `json:"id"`
	Email         string           `json:"email"`
	Username      string           `json:"username"`
	PasswordHash  string           `json:"password_hash"`
	IsActive      pgtype.Bool      `json:"is_active"`
	EmailVerified pgtype.Bool      `json:"email_verified"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

type UserSession struct {
	ID             int32            `json:"id"`
	UserID         int32            `json:"user_id"`
	SessionToken   string           `json:"session_token"`
	IpAddress      pgtype.Text      `json:"ip_address"`
	UserAgent      pgtype.Text      `json:"user_agent"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	LastActivityAt pgtype.Timestamp `json:"last_activity_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
