// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	CountActiveUserSessions(ctx context.Context, userID int32) (int64, error)
	CountFailedRequests(ctx context.Context, apiTokenID int32) (int64, error)
	CountSuccessfulRequests(ctx context.Context, apiTokenID int32) (int64, error)
	CountUserActiveTokens(ctx context.Context, userID int32) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error)
	CreateTokenUsageLog(ctx context.Context, arg CreateTokenUsageLogParams) (TokenUsageLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	DeleteApiToken(ctx context.Context, id int32) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteRole(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetApiTokenByID(ctx context.Context, id int32) (ApiToken, error)
	GetAuditLogsByAction(ctx context.Context, arg GetAuditLogsByActionParams) ([]AuditLog, error)
	GetAuditLogsInDateRange(ctx context.Context, arg GetAuditLogsInDateRangeParams) ([]AuditLog, error)
	GetAverageResponseTime(ctx context.Context, apiTokenID int32) (float64, error)
	GetRoleByID(ctx context.Context, id int32) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSubscriptionByID(ctx context.Context, id int32) (Subscription, error)
	GetSubscriptionPlanByID(ctx context.Context, id int32) (SubscriptionPlan, error)
	GetSubscriptionPlanByType(ctx context.Context, planType string) (SubscriptionPlan, error)
	GetTokenUsageLogs(ctx context.Context, arg GetTokenUsageLogsParams) ([]TokenUsageLog, error)
	GetTokenUsageLogsInDateRange(ctx context.Context, arg GetTokenUsageLogsInDateRangeParams) ([]TokenUsageLog, error)
	GetUserActiveSubscription(ctx context.Context, userID int32) (Subscription, error)
	GetUserAuditLogs(ctx context.Context, arg GetUserAuditLogsParams) ([]AuditLog, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRoles(ctx context.Context, userID int32) ([]Role, error)
	GetUserSessionByID(ctx context.Context, id int32) (UserSession, error)
	GetUserSessionByToken(ctx context.Context, sessionToken string) (UserSession, error)
	GetUserSubscription(ctx context.Context, userID int32) (Subscription, error)
	GetUserTokenUsageLogs(ctx context.Context, arg GetUserTokenUsageLogsParams) ([]TokenUsageLog, error)
	IncrementSubscriptionUsage(ctx context.Context, id int32) (Subscription, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListExpiredApiTokens(ctx context.Context) ([]ApiToken, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error)
	ListUserApiTokens(ctx context.Context, userID int32) ([]ApiToken, error)
	ListUserSessions(ctx context.Context, userID int32) ([]UserSession, error)
	ListUserSubscriptions(ctx context.Context, userID int32) ([]Subscription, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	ResetSubscriptionUsage(ctx context.Context, id int32) (Subscription, error)
	RevokeAllUserSessions(ctx context.Context, userID int32) error
	RevokeApiToken(ctx context.Context, id int32) (ApiToken, error)
	RevokeUserSession(ctx context.Context, id int32) error
	UpdateApiTokenLastUsed(ctx context.Context, id int32) (ApiToken, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSubscriptionCurrentUsage(ctx context.Context, arg UpdateSubscriptionCurrentUsageParams) (Subscription, error)
	UpdateSubscriptionIsActive(ctx context.Context, arg UpdateSubscriptionIsActiveParams) (Subscription, error)
	UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) (User, error)
	UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) (User, error)
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error)
	UpdateUserSessionActivity(ctx context.Context, id int32) (UserSession, error)
}

var _ Querier = (*Queries)(nil)
