// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, max_tokens_per_month, current_usage, usage_reset_date)
VALUES ($1, $2, $3, $4, NOW(), $5, $6, 0, NOW())
RETURNING id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID             int32            `json:"user_id"`
	SubscriptionPlanID int32            `json:"subscription_plan_id"`
	PlanType           string           `json:"plan_type"`
	IsActive           pgtype.Bool      `json:"is_active"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	MaxTokensPerMonth  int32            `json:"max_tokens_per_month"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.SubscriptionPlanID,
		arg.PlanType,
		arg.IsActive,
		arg.ExpiresAt,
		arg.MaxTokensPerMonth,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserActiveSubscription = `-- name: GetUserActiveSubscription :one
SELECT id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
FROM subscriptions
WHERE user_id = $1 AND is_active = true AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetUserActiveSubscription(ctx context.Context, userID int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, getUserActiveSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
FROM subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetUserSubscription(ctx context.Context, userID int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSubscriptionUsage = `-- name: IncrementSubscriptionUsage :one
UPDATE subscriptions
SET current_usage = current_usage + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
`

func (q *Queries) IncrementSubscriptionUsage(ctx context.Context, id int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, incrementSubscriptionUsage, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
FROM subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserSubscriptions(ctx context.Context, userID int32) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionPlanID,
			&i.PlanType,
			&i.IsActive,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.RenewalDate,
			&i.MaxTokensPerMonth,
			&i.CurrentUsage,
			&i.UsageResetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSubscriptionUsage = `-- name: ResetSubscriptionUsage :one
UPDATE subscriptions
SET current_usage = 0, usage_reset_date = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
`

func (q *Queries) ResetSubscriptionUsage(ctx context.Context, id int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, resetSubscriptionUsage, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionCurrentUsage = `-- name: UpdateSubscriptionCurrentUsage :one
UPDATE subscriptions
SET current_usage = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
`

type UpdateSubscriptionCurrentUsageParams struct {
	ID           int32       `json:"id"`
	CurrentUsage pgtype.Int4 `json:"current_usage"`
}

func (q *Queries) UpdateSubscriptionCurrentUsage(ctx context.Context, arg UpdateSubscriptionCurrentUsageParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionCurrentUsage, arg.ID, arg.CurrentUsage)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionIsActive = `-- name: UpdateSubscriptionIsActive :one
UPDATE subscriptions
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, subscription_plan_id, plan_type, is_active, started_at, expires_at, renewal_date, max_tokens_per_month, current_usage, usage_reset_date, created_at, updated_at
`

type UpdateSubscriptionIsActiveParams struct {
	ID       int32       `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateSubscriptionIsActive(ctx context.Context, arg UpdateSubscriptionIsActiveParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionIsActive, arg.ID, arg.IsActive)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionPlanID,
		&i.PlanType,
		&i.IsActive,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.RenewalDate,
		&i.MaxTokensPerMonth,
		&i.CurrentUsage,
		&i.UsageResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
