// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscriptionPlan = `-- name: CreateSubscriptionPlan :one
INSERT INTO subscription_plans (name, plan_type, description, max_tokens_per_month, max_api_calls_per_day, price, features, trial_duration_days, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, plan_type, description, max_tokens_per_month, max_api_calls_per_day, price, features, trial_duration_days, is_active, created_at, updated_at
`

type CreateSubscriptionPlanParams struct {
	Name              string         `json:"name"`
	PlanType          string         `json:"plan_type"`
	Description       pgtype.Text    `json:"description"`
	MaxTokensPerMonth int32          `json:"max_tokens_per_month"`
	MaxApiCallsPerDay int32          `json:"max_api_calls_per_day"`
	Price             pgtype.Numeric `json:"price"`
	Features          []byte         `json:"features"`
	TrialDurationDays pgtype.Int4    `json:"trial_duration_days"`
	IsActive          pgtype.Bool    `json:"is_active"`
}

func (q *Queries) CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPlan,
		arg.Name,
		arg.PlanType,
		arg.Description,
		arg.MaxTokensPerMonth,
		arg.MaxApiCallsPerDay,
		arg.Price,
		arg.Features,
		arg.TrialDurationDays,
		arg.IsActive,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.Description,
		&i.MaxTokensPerMonth,
		&i.MaxApiCallsPerDay,
		&i.Price,
		&i.Features,
		&i.TrialDurationDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionPlanByID = `-- name: GetSubscriptionPlanByID :one
SELECT id, name, plan_type, description, max_tokens_per_month, max_api_calls_per_day, price, features, trial_duration_days, is_active, created_at, updated_at
FROM subscription_plans
WHERE id = $1
`

func (q *Queries) GetSubscriptionPlanByID(ctx context.Context, id int32) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByID, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.Description,
		&i.MaxTokensPerMonth,
		&i.MaxApiCallsPerDay,
		&i.Price,
		&i.Features,
		&i.TrialDurationDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionPlanByType = `-- name: GetSubscriptionPlanByType :one
SELECT id, name, plan_type, description, max_tokens_per_month, max_api_calls_per_day, price, features, trial_duration_days, is_active, created_at, updated_at
FROM subscription_plans
WHERE plan_type = $1
`

func (q *Queries) GetSubscriptionPlanByType(ctx context.Context, planType string) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByType, planType)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.Description,
		&i.MaxTokensPerMonth,
		&i.MaxApiCallsPerDay,
		&i.Price,
		&i.Features,
		&i.TrialDurationDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionPlans = `-- name: ListSubscriptionPlans :many
SELECT id, name, plan_type, description, max_tokens_per_month, max_api_calls_per_day, price, features, trial_duration_days, is_active, created_at, updated_at
FROM subscription_plans
WHERE is_active = true
ORDER BY id
`

func (q *Queries) ListSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPlan
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlanType,
			&i.Description,
			&i.MaxTokensPerMonth,
			&i.MaxApiCallsPerDay,
			&i.Price,
			&i.Features,
			&i.TrialDurationDays,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :one
UPDATE subscription_plans
SET name = $2, description = $3, max_tokens_per_month = $4, max_api_calls_per_day = $5, price = $6, features = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, name, plan_type, description, max_tokens_per_month, max_api_calls_per_day, price, features, trial_duration_days, is_active, created_at, updated_at
`

type UpdateSubscriptionPlanParams struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	Description       pgtype.Text    `json:"description"`
	MaxTokensPerMonth int32          `json:"max_tokens_per_month"`
	MaxApiCallsPerDay int32          `json:"max_api_calls_per_day"`
	Price             pgtype.Numeric `json:"price"`
	Features          []byte         `json:"features"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MaxTokensPerMonth,
		arg.MaxApiCallsPerDay,
		arg.Price,
		arg.Features,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.Description,
		&i.MaxTokensPerMonth,
		&i.MaxApiCallsPerDay,
		&i.Price,
		&i.Features,
		&i.TrialDurationDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
