// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token_usage_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFailedRequests = `-- name: CountFailedRequests :one
SELECT COUNT(*) FROM token_usage_logs
WHERE api_token_id = $1 AND (status_code < 200 OR status_code >= 300)
`

func (q *Queries) CountFailedRequests(ctx context.Context, apiTokenID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedRequests, apiTokenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuccessfulRequests = `-- name: CountSuccessfulRequests :one
SELECT COUNT(*) FROM token_usage_logs
WHERE api_token_id = $1 AND status_code >= 200 AND status_code < 300
`

func (q *Queries) CountSuccessfulRequests(ctx context.Context, apiTokenID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulRequests, apiTokenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTokenUsageLog = `-- name: CreateTokenUsageLog :one
INSERT INTO token_usage_logs (api_token_id, user_id, endpoint, method, status_code, response_time, data_size, error_message, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, api_token_id, user_id, endpoint, method, status_code, response_time, data_size, error_message, ip_address, user_agent, created_at
`

type CreateTokenUsageLogParams struct {
	ApiTokenID   int32       `json:"api_token_id"`
	UserID       int32       `json:"user_id"`
	Endpoint     string      `json:"endpoint"`
	Method       string      `json:"method"`
	StatusCode   int32       `json:"status_code"`
	ResponseTime pgtype.Int8 `json:"response_time"`
	DataSize     pgtype.Int8 `json:"data_size"`
	ErrorMessage pgtype.Text `json:"error_message"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateTokenUsageLog(ctx context.Context, arg CreateTokenUsageLogParams) (TokenUsageLog, error) {
	row := q.db.QueryRow(ctx, createTokenUsageLog,
		arg.ApiTokenID,
		arg.UserID,
		arg.Endpoint,
		arg.Method,
		arg.StatusCode,
		arg.ResponseTime,
		arg.DataSize,
		arg.ErrorMessage,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i TokenUsageLog
	err := row.Scan(
		&i.ID,
		&i.ApiTokenID,
		&i.UserID,
		&i.Endpoint,
		&i.Method,
		&i.StatusCode,
		&i.ResponseTime,
		&i.DataSize,
		&i.ErrorMessage,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAverageResponseTime = `-- name: GetAverageResponseTime :one
SELECT AVG(response_time) as avg_response_time FROM token_usage_logs
WHERE api_token_id = $1
`

func (q *Queries) GetAverageResponseTime(ctx context.Context, apiTokenID int32) (float64, error) {
	row := q.db.QueryRow(ctx, getAverageResponseTime, apiTokenID)
	var avg_response_time float64
	err := row.Scan(&avg_response_time)
	return avg_response_time, err
}

const getTokenUsageLogs = `-- name: GetTokenUsageLogs :many
SELECT id, api_token_id, user_id, endpoint, method, status_code, response_time, data_size, error_message, ip_address, user_agent, created_at
FROM token_usage_logs
WHERE api_token_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTokenUsageLogsParams struct {
	ApiTokenID int32 `json:"api_token_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) GetTokenUsageLogs(ctx context.Context, arg GetTokenUsageLogsParams) ([]TokenUsageLog, error) {
	rows, err := q.db.Query(ctx, getTokenUsageLogs, arg.ApiTokenID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokenUsageLog
	for rows.Next() {
		var i TokenUsageLog
		if err := rows.Scan(
			&i.ID,
			&i.ApiTokenID,
			&i.UserID,
			&i.Endpoint,
			&i.Method,
			&i.StatusCode,
			&i.ResponseTime,
			&i.DataSize,
			&i.ErrorMessage,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenUsageLogsInDateRange = `-- name: GetTokenUsageLogsInDateRange :many
SELECT id, api_token_id, user_id, endpoint, method, status_code, response_time, data_size, error_message, ip_address, user_agent, created_at
FROM token_usage_logs
WHERE api_token_id = $1 AND created_at >= $2 AND created_at <= $3
ORDER BY created_at DESC
`

type GetTokenUsageLogsInDateRangeParams struct {
	ApiTokenID  int32            `json:"api_token_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) GetTokenUsageLogsInDateRange(ctx context.Context, arg GetTokenUsageLogsInDateRangeParams) ([]TokenUsageLog, error) {
	rows, err := q.db.Query(ctx, getTokenUsageLogsInDateRange, arg.ApiTokenID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokenUsageLog
	for rows.Next() {
		var i TokenUsageLog
		if err := rows.Scan(
			&i.ID,
			&i.ApiTokenID,
			&i.UserID,
			&i.Endpoint,
			&i.Method,
			&i.StatusCode,
			&i.ResponseTime,
			&i.DataSize,
			&i.ErrorMessage,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTokenUsageLogs = `-- name: GetUserTokenUsageLogs :many
SELECT id, api_token_id, user_id, endpoint, method, status_code, response_time, data_size, error_message, ip_address, user_agent, created_at
FROM token_usage_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserTokenUsageLogsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUserTokenUsageLogs(ctx context.Context, arg GetUserTokenUsageLogsParams) ([]TokenUsageLog, error) {
	rows, err := q.db.Query(ctx, getUserTokenUsageLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokenUsageLog
	for rows.Next() {
		var i TokenUsageLog
		if err := rows.Scan(
			&i.ID,
			&i.ApiTokenID,
			&i.UserID,
			&i.Endpoint,
			&i.Method,
			&i.StatusCode,
			&i.ResponseTime,
			&i.DataSize,
			&i.ErrorMessage,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
