// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUserSessions = `-- name: CountActiveUserSessions :one
SELECT COUNT(*) FROM user_sessions
WHERE user_id = $1 AND expires_at > NOW()
`

func (q *Queries) CountActiveUserSessions(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUserSessions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (user_id, session_token, ip_address, user_agent, expires_at, last_activity_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, user_id, session_token, ip_address, user_agent, expires_at, last_activity_at, created_at, updated_at
`

type CreateUserSessionParams struct {
	UserID       int32            `json:"user_id"`
	SessionToken string           `json:"session_token"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.SessionToken,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getUserSessionByID = `-- name: GetUserSessionByID :one
SELECT id, user_id, session_token, ip_address, user_agent, expires_at, last_activity_at, created_at, updated_at
FROM user_sessions
WHERE id = $1
`

func (q *Queries) GetUserSessionByID(ctx context.Context, id int32) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionByToken = `-- name: GetUserSessionByToken :one
SELECT id, user_id, session_token, ip_address, user_agent, expires_at, last_activity_at, created_at, updated_at
FROM user_sessions
WHERE session_token = $1 AND expires_at > NOW()
`

func (q *Queries) GetUserSessionByToken(ctx context.Context, sessionToken string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByToken, sessionToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, session_token, ip_address, user_agent, expires_at, last_activity_at, created_at, updated_at
FROM user_sessions
WHERE user_id = $1 AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID int32) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionToken,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
DELETE FROM user_sessions
WHERE id = $1
`

func (q *Queries) RevokeUserSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeUserSession, id)
	return err
}

const updateUserSessionActivity = `-- name: UpdateUserSessionActivity :one
UPDATE user_sessions
SET last_activity_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, session_token, ip_address, user_agent, expires_at, last_activity_at, created_at, updated_at
`

func (q *Queries) UpdateUserSessionActivity(ctx context.Context, id int32) (UserSession, error) {
	row := q.db.QueryRow(ctx, updateUserSessionActivity, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
